# Generated by Django 3.2.6 on 2021-08-24 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Event_Type',
            new_name='Type_Event',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='restaurant',
            new_name='place',
        ),
        migrations.AddField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='recurring',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='tix_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tix_required',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ManyToManyField(to='api.Type_Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.place'),
            preserve_default=False,
        ),
    ]
