# Generated by Django 3.2.6 on 2021-08-24 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210824_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_date',
            name='when',
        ),
        migrations.AddField(
            model_name='event_date',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event_date',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='event_date',
            name='where',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
    ]
