# Generated by Django 3.2.6 on 2021-08-24 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210824_0454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event_Date',
            new_name='EventDate',
        ),
        migrations.RenameModel(
            old_name='Type_Event',
            new_name='TypeEvent',
        ),
    ]
