# Generated by Django 3.2.6 on 2021-08-25 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210824_0457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenity',
            old_name='name',
            new_name='amenity',
        ),
        migrations.RenameField(
            model_name='subtype',
            old_name='SubType',
            new_name='subtype',
        ),
    ]
