# Generated by Django 3.2.6 on 2021-08-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210825_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='open_close',
            field=models.BooleanField(choices=[(True, 'Open'), (False, 'Close')]),
        ),
    ]
