# Generated by Django 3.2.6 on 2021-08-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_time_open_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='open_now',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
