# Generated by Django 3.2.6 on 2021-09-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_place_open_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='short_description',
            field=models.TextField(null=True),
        ),
    ]
