# Generated by Django 3.2.6 on 2021-09-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210909_1515'),
        ('api', '0012_auto_20210909_1539'),
        ('api', '0013_alter_place_description'),
        ('api', '0013_alter_place_subtype'),
    ]

    operations = [
    ]
