# Generated by Django 3.2.6 on 2021-09-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_20210913_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
