# Generated by Django 3.2.6 on 2021-09-14 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_event_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
