# Generated by Django 3.2.6 on 2021-09-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_event_when'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='when',
        ),
    ]
