# Generated by Django 3.2.6 on 2021-09-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_event_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='when',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
